#!/usr/bin/env python

import os

test_list = [
    '1',
    '2',
    '3',
    'iter',
    'ls',
]

CXXFLAGS = '-g -Wall -Wextra -std=c++0x -L../luacapi/'
for testname in test_list:
    ccfn = 'test%s.cc' % testname
    cmd = 'g++ %s %s -llua -ldl && ./a.out' % (CXXFLAGS, ccfn)
    print cmd
    os.system(cmd)

print 'All testcases OK.'
