#!/usr/bin/env python

import os
import sys

test_list = [
    '1',
    '2',
    '3',
    'iter',
    'ls',
    'ns',
    'ns2',
]

CXXFLAGS = '-g -Wall -Wextra -std=c++0x -L../luacapi/'
for testname in test_list:
    ccfn = 'test%s.cc' % testname
    cmd = 'g++ %s %s -llua -ldl && ./a.out' % (CXXFLAGS, ccfn)
    print cmd
    code = os.system(cmd)
    if code != 0:
        print 'Failed: %s (return code = %s)' % (ccfn, code)
        sys.exit(code)

print 'All testcases OK.'
